Flexberry/ember-flexberry

.gitignore, blueprints/ember-flexberry/index.js, blueprints/flexberry-application/index.js, blueprints/flexberry-application/index.ts, blueprints/flexberry-list-form/index.js, blueprints/flexberry-model/files/__root__/models/__name__.js, blueprints/flexberry-model/files/__root__/serializers/__name__.js, blueprints/flexberry-model/index.js, blueprints/flexberry-model/index.ts, blueprints/flexberry-model/index0.js
Fix serializer inheritance: task 104745
=> Fix serializer inheritance: task 104745

addon/components/object-list-view.js, addon/controllers/edit-form.js, app/templates/components/flexberry-groupedit.hbs, app/templates/components/flexberry-objectlistview.hbs
1. Remove hard-coded alert/confirm messages from components/controllers/routes. All checks should be placed in application code.
2. Move code from actions (save, delete, close, etc.) to appropriate methods of edit form controller. These actions should only call that methods.
[TFS #101204](http://dis-tfs:8080/Common/Flex/_workitems?id=101204&_a=edit&fullScreen=true)
=> Refactoring technology actions

CHANGELOG.md, addon/components/flexberry-groupedit.js, addon/components/flexberry-objectlistview.js, addon/mixins/flexberry-groupedit-route.js, addon/mixins/flexberry-objectlistview-route.js, addon/routes/list-form.js, app/templates/components/flexberry-groupedit.hbs, app/templates/components/flexberry-objectlistview.hbs, tests/dummy/app/templates/employee.hbs, tests/dummy/app/templates/employees.hbs, tests/dummy/app/templates/orders.hbs
=> Fix actions for flexberry-objectlistview and flexberry-groupedit

blueprints/flexberry-edit-form/files/__root__/templates/__name__.hbs, blueprints/flexberry-edit-form/snippets/flexberry-checkbox.hbs
=> Fix label for checkbox

blueprints/flexberry-edit-form/files/__root__/templates/__name__.hbs
=> Add localization for edit-form buttons

blueprints/flexberry-edit-form/files/__root__/templates/__name__.hbs, blueprints/flexberry-list-form/files/__root__/templates/__name__.hbs
=> Fix forms caption

CHANGELOG.md, addon/components/olv-toolbar.js, app/templates/components/olv-toolbar.hbs
=> Add removeFilter action for flexberry-objectlistview

addon/mixins/flexberry-lookup.js
If backend slow, then lookup not close after select item.
=> Mystical lookup behavior

blueprints/flexberry-application/files/__root__/adapters/application.js
=> Fix after rename ember-flexberry-projections

addon/controllers/lookup-dialog.js, app/templates/lookup-dialog-content.hbs, app/templates/mobile/components/flexberry-lookup.hbs
=> Fix flexberry-lookup for mobile

scripts/test-generator.sh
=> Fix generate route index

blueprints/flexberry-list-form/files/__root__/templates/__name__.hbs, scripts/test-generator.sh
=> Fix flexberry-objectlistview remove action rowClick 

addon/components/flexberry-file.js, app/templates/components/flexberry-file.hbs
=> Fix locate for flexberry-file component

blueprints/flexberry-model/index.js, blueprints/flexberry-model/index.ts
=> Feature projections generation update

blueprints/flexberry-edit-form/snippets/flexberry-lookup.hbs
=> Fix flexberry-lookup generation

blueprints/flexberry-core/files/__root__/templates/application-with-submenu.hbs, blueprints/flexberry-core/files/__root__/templates/application.hbs, blueprints/flexberry-core/files/__root__/templates/mobile/application.hbs, blueprints/flexberry-edit-form/files/__root__/templates/__name__.hbs
=> Fix templates for generator

blueprints/flexberry-edit-form/index.js, blueprints/flexberry-edit-form/index.ts
=> Fix flexberry-edit-form generation error

blueprints/flexberry-edit-form/files/__root__/routes/__name__/new.js
[TFS#104867](http://dis-tfs:8080/Common/Flex/_workitems?_a=edit&id=104867).
=> Fix flexberry-edit-form blueprints

CHANGELOG.md, addon/mixins/flexberry-objectlistview-route.js, addon/mixins/limited-controller.js, addon/mixins/limited-route.js, addon/routes/list-form.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/limit-function-example.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/limit-function-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/models/ember-flexberry-dummy-suggestion.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/limit-function-example.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/limit-function-example.hbs
TFS#106606
Now limit predicate is not visible as query parameter.
=> Repair opportunity to set limits on FlexberryObjectlistviewComponent

blueprints/flexberry-list-form/files/__root__/templates/__name__.hbs
=> Fix editFormRoute property for generator

tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/dropdown-mode-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/models/ember-flexberry-dummy-suggestion-type.js, tests/dummy/app/models/ember-flexberry-dummy-suggestion.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-lookup/dropdown-mode-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/dropdown-mode-example.hbs
Added example on lookup in dropdown mode on dummy.
=> Feature lookup dropdown example

blueprints/flexberry-list-form/files/__root__/templates/__name__.hbs
[TFS#105068](http://dis-tfs:8080/Common/Flex/_workitems?_a=edit&id=105068) (p.5).
=> Fix flexberry-list-form blueprints

tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/settings-example.hbs
=> Feature change dummy

addon/components/flexberry-lookup.js, addon/components/modal-dialog.js, addon/components/object-list-view.js, app/templates/components/flexberry-lookup.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs
(TFS#107285)
1. Fix lookup in dropdown mode (now it can save selected value but some problems still exist).
2. Fix error on lookup modal window in IE.
(TFS#107691)
3. Fix not working sorting on Objectlistview at Firefox.
=> Fix some found bugs

.travis.yml, README.md, firebase.json
Automatic deployment on new [Firebase](https://firebase.google.com/).
=> Fix firebase deploy

CHANGELOG.md, addon/components/flexberry-textarea.js, addon/components/flexberry-textbox.js
=> Remove disabled class for wrapper flexberry-textbox & flexberry-textarea

addon/components/flexberry-menu.js
=> Fix configurateItems for flexberry-menu

app/templates/components/flexberry-objectlistview.hbs
[TFS#107710](http://dis-tfs:8080/Common/CaseberrySupport/_workitems?_a=edit&id=107710).
=> Fix switch for perpage value on FlexberryObjectlistview

tests/dummy/app/models/ember-flexberry-dummy-suggestion.js
=> Fix example olv with filter.

tests/dummy/app/templates/mobile/application.hbs
=> Add locales for mobile.

app/templates/components/flexberry-lookup.hbs, tests/dummy/app/routes/base-edit-form.js, tests/dummy/app/routes/ember-flexberry-dummy-application-user-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-comment-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-localization-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-type-edit.js
=> Fix found bugs

addon/components/flexberry-toggler.js, tests/dummy/app/controllers/components-examples/flexberry-toggler/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-toggler/settings-example.hbs
=> Fix flexberry-toggler component

app/templates/components/object-list-view-single-column-cell.hbs, app/templates/components/object-list-view.hbs
tfs#107909
There was no readonly flag propagation to mobile component.
=> Fix readonly problem in groupedit in mobile variant

addon/components/flexberry-dropdown.js, addon/components/flexberry-lookup.js, addon/locales/en/translations.js, addon/locales/ru/translations.js, app/templates/components/flexberry-lookup.hbs
=> Fix dropdown lookup

CHANGELOG.md, addon/components/flexberry-checkbox.js, app/templates/components/flexberry-checkbox.hbs, tests/dummy/app/controllers/components-examples/flexberry-checkbox/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-checkbox/settings-example.hbs
Its need becase flexberry-checkbox has tagName="".
=> Add class for checkbox

tests/dummy/app/controllers/components-examples/flexberry-menu/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-menu/settings-example.hbs
=> Add component template for flexberry-menu example

addon/components/flexberry-dropdown.js
=> Add convert of items and value of dropdown to string before check

blueprints/flexberry-edit-form/files/__root__/controllers/__name__.js, blueprints/flexberry-edit-form/index.js, blueprints/flexberry-edit-form/index.ts
[TFS#108234](http://dis-tfs:8080/Common/CASEBERRY/_workitems?_a=edit&id=108234).
=> Error generate edit form without a corresponding list form

tests/dummy/app/controllers/ember-flexberry-dummy-application-user-edit.js, tests/dummy/app/controllers/ember-flexberry-dummy-comment-edit.js, tests/dummy/app/controllers/ember-flexberry-dummy-localization-edit.js, tests/dummy/app/controllers/ember-flexberry-dummy-suggestion-edit.js, tests/dummy/app/controllers/ember-flexberry-dummy-suggestion-type-edit.js, tests/dummy/app/mixins/base-edit-form-mixin.js, tests/dummy/app/mixins/edit-form-controller-operations-indication.js, tests/dummy/app/mixins/edit-form-route-operations-indication.js, tests/dummy/app/routes/ember-flexberry-dummy-application-user-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-application-user-edit/new.js, tests/dummy/app/routes/ember-flexberry-dummy-comment-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-comment-edit/new.js, tests/dummy/app/routes/ember-flexberry-dummy-localization-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-localization-edit/new.js, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-edit/new.js, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-type-edit.js, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-type-edit/new.js
=> Fix save object with detail.

blueprints/flexberry-edit-form/files/__root__/templates/__name__.hbs, blueprints/flexberry-edit-form/snippets/flexberry-checkbox.hbs, blueprints/flexberry-edit-form/snippets/flexberry-datepicker.hbs, blueprints/flexberry-edit-form/snippets/flexberry-dropdown.hbs, blueprints/flexberry-edit-form/snippets/flexberry-field.hbs, blueprints/flexberry-edit-form/snippets/flexberry-file.hbs, blueprints/flexberry-edit-form/snippets/flexberry-groupedit.hbs, blueprints/flexberry-edit-form/snippets/flexberry-lookup.hbs, blueprints/flexberry-edit-form/snippets/flexberry-textbox.hbs, blueprints/flexberry-model/index.js, blueprints/flexberry-model/index.ts, blueprints/typings/MetadataClasses.d.ts, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-test-poly-child-edit.json, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-test-poly-edit.json, vendor/flexberry/dummy-metadata/list-forms/ember-flexberry-dummy-test-poly-child-list.json, vendor/flexberry/dummy-metadata/list-forms/ember-flexberry-dummy-test-poly-list.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-comment-vote.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-comment.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-localized-suggestion-type.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-suggestion-file.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-suggestion-type.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-suggestion.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-test-poly-base.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-test-poly-child.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-test-poly.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-vote.json, vendor/flexberry/dummy-metadata/schema-model.json
=> Feature generation validations presence belongsTo releation

addon/components/flexberry-menuitem.js, tests/dummy/app/controllers/components-examples/flexberry-menu/settings-example.js
=> Fix flexberry menu example

addon/mixins/reload-list-mixin.js
If is ok, take after this [pull request](https://github.com/Flexberry/ember-flexberry-data/pull/12).
=> Not use empty string for sorting

blueprints/flexberry-edit-form/files/__root__/controllers/__name__.js, blueprints/flexberry-edit-form/index.js, blueprints/flexberry-edit-form/index.ts, blueprints/flexberry-edit-form/snippets/getCellComponent-flexberry-lookup.js, blueprints/flexberry-edit-form/snippets/getCellComponent-function.js, blueprints/typings/MetadataClasses.d.ts, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-comment-edit.json, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-suggestion-edit.json, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-suggestion-type-edit.json, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-test-poly-edit.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-test-poly-base.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-test-poly-child.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-test-poly.json, vendor/flexberry/dummy-metadata/schema-edit-form.json
=> Feature customization lookups in flexberry-groupedit

addon/components/mobile/flexberry-file.js, app/templates/mobile/components/flexberry-file.hbs
=> Fix flexberry-menu inside flexberry-file component

tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/lookup-block-form-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/models/ember-flexberry-dummy-suggestion.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-lookup/lookup-block-form-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/lookup-block-form-example.hbs, tests/dummy/app/templates/mobile/components-examples/flexberry-lookup/lookup-block-form-example.hbs
=> Add example lookup in block form

CHANGELOG.md, addon/components/object-list-view.js, addon/mixins/flexberry-objectlistview-route.js, addon/mixins/paginated-controller.js, addon/mixins/paginated-route.js, addon/mixins/sortable-column.js, addon/mixins/sortable-controller.js, addon/mixins/sortable-route.js
=> Fix sorting in objectlistview for FF

CHANGELOG.md, addon/components/flexberry-menu.js, addon/components/flexberry-menuitem.js
=> Fix flexberry-menu for configuration of columns settings

tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/lookup-in-modal.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-lookup/lookup-in-modal.js, tests/dummy/app/templates/components-examples/flexberry-lookup/lookup-in-modal.hbs
=> Add example work lookup in modal

tests/dummy/app/controllers/components-examples/flexberry-datepicker/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-dropdown/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-field/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-file/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-groupedit/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-textarea/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-textbox/settings-example.js
=> fix work pleceholder in setting-example

CHANGELOG.md, addon/components/flexberry-objectlistview.js, addon/components/object-list-view.js, addon/components/olv-toolbar.js, addon/mixins/limited-controller.js, addon/mixins/limited-route.js, addon/mixins/reload-list-mixin.js, addon/routes/list-form.js, addon/services/objectlistview-events.js, app/templates/components/flexberry-objectlistview.hbs, app/templates/components/object-list-view.hbs, app/templates/components/olv-toolbar.hbs, app/templates/mobile/components/object-list-view.hbs, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/custom-filter.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/custom-filter.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/custom-filter.hbs, tests/dummy/app/templates/components-examples/flexberry-objectlistview/settings-example.hbs
[TFS#108150](http://dis-tfs:8080/Common/CASEBERRY/_workitems?_a=edit&id=108150).
=> Filters for OLV

addon/components/flexberry-lookup.js, addon/components/modal-dialog.js, addon/mixins/modal-application-route.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/lookup-in-modal.js, tests/dummy/app/templates/components-examples/flexberry-lookup/lookup-in-modal.hbs
=> Feature 111069 lookup inside modal

blueprints/ember-flexberry/index.js, blueprints/flexberry-core/files/.jscsrc, blueprints/flexberry-core/files/ember-cli-build.js, scripts/test-generator.sh
=> Feature generation file .jscsrc

tests/dummy/app/styles/app.scss
=> Fix mobile style

addon/components/flexberry-base-component.js, addon/components/object-list-view.js, app/templates/components/flexberry-objectlistview.hbs, app/templates/components/object-list-view.hbs, app/templates/components/olv-toolbar.hbs, app/templates/mobile/components/object-list-view.hbs
Button reset filters move in toolbar from body table.
=> Move button at FOLV in toolbar

CHANGELOG.md, addon/components/flexberry-datepicker.js, addon/components/flexberry-simpledatetime.js, addon/styles/addon.scss
=> Fix found bugs after release

CHANGELOG.md, addon/components/flexberry-lookup.js
=> Fix displayAttributeName for flexberry-lookup

tests/dummy/app/controllers/components-examples/flexberry-datepicker/settings-example.js
=> Fix default values max and min date

addon/components/object-list-view.js, app/templates/components/object-list-view-header-cell.hbs
tfs #108285
Needs when you change locales in app.
=> Fix caption for objectlistview

CHANGELOG.md, addon/components/flexberry-objectlistview.js, addon/components/mobile/object-list-view-row.js, addon/components/object-list-view-row.js, addon/components/object-list-view.js, addon/controllers/list-form.js, addon/mixins/flexberry-objectlistview-hierarchical-controller.js, addon/mixins/flexberry-objectlistview-hierarchical-route.js, addon/mixins/reload-list-mixin.js, addon/routes/list-form.js, app/components/mobile/object-list-view-row.js, app/components/object-list-view-row.js, app/templates/components/flexberry-objectlistview.hbs, app/templates/components/object-list-view-row.hbs, app/templates/components/object-list-view.hbs, app/templates/components/olv-toolbar.hbs, app/templates/mobile/components/object-list-view-row.hbs, app/templates/mobile/components/object-list-view.hbs
[TFS#110618](http://dis-tfs:8080/Common/CASEBERRY/_workitems?_a=edit&id=110618).
=> Hierarchical mode for FlexberryObjectlistview

.gitignore, CHANGELOG.md, blueprints/flexberry-application/index.js, blueprints/flexberry-application/index.ts, blueprints/flexberry-group/index.js, blueprints/flexberry-group/index.ts
=> Fix speed up generation process

CHANGELOG.md, blueprints/flexberry-core/files/__root__/app.js, blueprints/flexberry-core/files/__root__/models/custom-inflector-rules.js, blueprints/flexberry-core/index.js, blueprints/flexberry-core/index.ts, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-comment-edit.json, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-suggestion-edit.json, vendor/flexberry/dummy-metadata/edit-forms/ember-flexberry-dummy-suggestion-type-edit.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-comment-vote.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-comment.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-localized-suggestion-type.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-suggestion-file.json, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-vote.json
=> Feature generation models pluralization

tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-dropdown/items-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/templates/components-examples/flexberry-dropdown/items-example.hbs
=> Add example of different types of items for flexberry-dropdown

tests/dummy/app/controllers/components-examples/flexberry-dropdown/items-example.js, tests/dummy/app/templates/components-examples/flexberry-dropdown/items-example.hbs
=> Fix example for flexberry-dropdown

tests/dummy/app/models/ember-flexberry-dummy-application-user.js, vendor/flexberry/dummy-metadata/models/ember-flexberry-dummy-application-user.json
Now using decimal type for decimal numbers in models
=> Feature add decimal attrs

CHANGELOG.md, addon/resolver.js
Add ability to specify resources that should be resolved with origin resolving path (without considering device type detection)
=> Feature improve resolver

CHANGELOG.md, app/templates/components/flexberry-textarea.hbs
Add support of HTML attributes for `flexberry-textarea` component
=> Feature add html attributes to flexberry textarea

tests/dummy/app/controllers/components-examples/flexberry-groupedit/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-groupedit/settings-example.hbs
Fix example for flexberry-groupedit.
=> Delete controller's properties for route.

tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-dropdown/empty-value-example.js, tests/dummy/app/enums/components-examples/flexberry-dropdown/empty-value-example/enumeration.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/models/components-examples/flexberry-dropdown/empty-value-example/base.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-dropdown/empty-value-example.js, tests/dummy/app/templates/components-examples/flexberry-dropdown/empty-value-example.hbs
=> Add test dropdown with empty value

CHANGELOG.md, addon/components/flexberry-toggler.js, app/templates/components/flexberry-toggler.hbs, tests/dummy/app/controllers/components-examples/flexberry-toggler/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-toggler/settings-example.hbs
=> Fix expanded property & add iconClass for lexberry-toggler component

CHANGELOG.md, addon/components/object-list-view.js, addon/styles/components/object-list-view.scss
=> Fix the width of the first column in objectlistview component

CHANGELOG.md, addon/controllers/edit-form.js
=> Fix state isDeleted after failed delete

CHANGELOG.md, addon/components/flexberry-file.js, addon/controllers/edit-form.js, app/templates/components/flexberry-file.hbs, tests/dummy/app/controllers/components-examples/flexberry-file/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-file/settings-example.hbs
Renamed property for input in flexberry-file.
=> Feature 115254 fix flexberry file

CHANGELOG.md, addon/components/flexberry-field.js, addon/components/flexberry-textbox.js, app/templates/components/flexberry-field.hbs, app/templates/components/flexberry-textbox.hbs
Default type is still 'text'. Also flexberry-textbox include same changes.
=> Add explicit type definition to flexberry-field

CHANGELOG.md, blueprints/flexberry-edit-form/snippets/flexberry-checkbox.hbs, blueprints/flexberry-edit-form/snippets/flexberry-datepicker.hbs, blueprints/flexberry-edit-form/snippets/flexberry-dropdown.hbs, blueprints/flexberry-edit-form/snippets/flexberry-field.hbs, blueprints/flexberry-edit-form/snippets/flexberry-file.hbs, blueprints/flexberry-edit-form/snippets/flexberry-groupedit.hbs, blueprints/flexberry-edit-form/snippets/flexberry-lookup.hbs, blueprints/flexberry-edit-form/snippets/flexberry-textbox.hbs
Remove old validator in top of the field, format generated code in hbs.
=> Remove top validator generation for props

CHANGELOG.md, addon/resolver.js
=> Replace includes to contains in resolver for support IE

CHANGELOG.md, addon/controllers/edit-form.js, addon/controllers/list-form.js, addon/mixins/flexberry-lookup-controller.js, addon/mixins/olv-toolbar-controller.js
=> Renamed mixin for olv-toolbar & flexberry-lookup

CHANGELOG.md, addon/components/object-list-view.js, app/templates/components/flexberry-groupedit.hbs, package.json, tests/dummy/app/controllers/ember-flexberry-dummy-suggestion-edit.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/configurate-rows.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs, tests/integration/components/flexberry-groupedit-test.js, tests/integration/components/object-list-view-test.js, vendor/ember-flexberry/register-version.js
=> Fix 112159 configurate row

CHANGELOG.md, addon/components/object-list-view.js, tests/dummy/app/models/ember-flexberry-dummy-suggestion.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/custom-filter.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/custom-filter.hbs
+ Fix building filters in OLV
+ Update model on OLV with filter example
=> Fix OLV filters

addon/adapters/new-platform-flexberry-services-lock.js, app/adapters/new-platform-flexberry-services-lock.js, tests/unit/adapters/new-platform-flexberry-services-lock-test.js
Specify id type for successful delete locks.
=> Adapter for lock model

CHANGELOG.md, addon/components/object-list-view.js, tests/dummy/app/controllers/ember-flexberry-dummy-suggestion-edit.js
=> Fix configurateRow for object-list-view

CHANGELOG.md, addon/components/flexberry-lookup.js, tests/dummy/app/templates/components-examples/flexberry-lookup/dropdown-mode-example.hbs
Several fix for `flexberry-lookup`. See CHANGELOG.md for more info.
=> Fix for lookup

CHANGELOG.md, addon/components/flexberry-lookup.js, app/templates/components/flexberry-dropdown.hbs, app/templates/components/flexberry-lookup.hbs, app/templates/mobile/components/flexberry-lookup.hbs, tests/dummy/app/templates/components-examples/flexberry-lookup/dropdown-mode-example.hbs
=> Fux lexberry-lookup in dropdown mode

tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs
Chenge lookup Type on Suggestions to lookup-dropdown.
=> Chenge lookup Type to lookup-dropdown.

CHANGELOG.md, addon/controllers/edit-form.js, app/templates/new-platform-flexberry-services-lock-edit.hbs, blueprints/flexberry-edit-form/files/app/templates/__name__.hbs, tests/dummy/app/mixins/edit-form-controller-operations-indication.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/on-edit-form/user.hbs, tests/dummy/app/templates/ember-flexberry-dummy-application-user-edit.hbs, tests/dummy/app/templates/ember-flexberry-dummy-comment-edit.hbs, tests/dummy/app/templates/ember-flexberry-dummy-localization-edit.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-type-edit.hbs
=> Feature 114900 loading edit form

CHANGELOG.md, app/services/log.js, tests/dummy/config/environment.js
=> Feature 116178 fix log service

CHANGELOG.md, addon/components/flexberry-dropdown.js, app/templates/components/flexberry-dropdown.hbs, tests/dummy/app/controllers/components-examples/flexberry-dropdown/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-dropdown/settings-example.hbs, tests/dummy/app/templates/ember-flexberry-dummy-application-user-edit.hbs
=> Add support of semantic-ui settings for flexberry-dropdown

addon/services/user-settings.js
Property `isUserSettingsServiceEnabled` of `user-settings` service should
be set with value from `useUserSettingsService` option of application
=> Fix constant disabling of user settings service

addon/components/object-list-view.js
Restore drag and drop columns width settings in object-list-view.
=> Fix object-list-view set columns resizing

addon/components/flexberry-simpleolv.js, addon/components/object-list-view.js, addon/routes/list-form.js, app/templates/components/flexberry-simpleolv.hbs, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-type-list.js, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-type-list.hbs
Fixed:
- Columns width
- Columns sorting
- Columns ordering
- Columns visibility
- Toolbar button
=> Fix columns user settings in `flexberry-simpleolv` component

tests/dummy/app/routes/components-examples/flexberry-simpleolv/configurate-rows.js, tests/dummy/app/routes/components-examples/flexberry-simpleolv/on-edit-form.js, tests/dummy/app/routes/components-examples/flexberry-simpleolv/selected-rows.js, tests/dummy/app/templates/components-examples/flexberry-simpleolv/configurate-rows.hbs, tests/dummy/app/templates/components-examples/flexberry-simpleolv/settings-example.hbs
=> fix tests simpleolv

addon/components/flexberry-simpleolv.js, addon/components/object-list-view.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/on-edit-form/user.js, tests/dummy/app/routes/components-examples/flexberry-simpleolv/on-edit-form/user.js
=> fix flexberry-simpleolv

CHANGELOG.md, addon/controllers/detail-edit-form.js, addon/controllers/edit-form.js
Sorry, i can not find words for `CHANGELOG.md`...
=> Fix close detail edit form

addon/components/flexberry-textbox.js, tests/integration/components/flexberry-textbox-test.js
Integration test for flexberry-textbox.
=> Integration test flexberry textbox

addon/components/flexberry-dropdown.js, tests/dummy/app/controllers/components-examples/flexberry-dropdown/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-dropdown/settings-example.hbs
=> fix settings example dropdown

app/templates/components/flexberry-textarea.hbs, tests/dummy/app/templates/components-examples/flexberry-textarea/settings-example.hbs, tests/integration/components/flexberry-textarea-test.js
Add integration test for flexberry-textarea.
=> Feature 119275 integration test flexberry textarea

tests/dummy/app/controllers/components-examples/flexberry-menu/settings-example.js
=> fix settings example flexberry-menu

tests/integration/components/flexberry-field-test.js
Fix integration test for flexberry-field.
=> Feature 117475 integration test flexberry field

CHANGELOG.md, addon/components/flexberry-groupedit.js, addon/components/flexberry-objectlistview.js, app/templates/components/flexberry-groupedit.hbs, app/templates/components/flexberry-objectlistview.hbs, app/templates/components/object-list-view-row.hbs, app/templates/components/object-list-view.hbs, blueprints/ember-flexberry/index.js, package.json
Components:
* `flexberry-groupedit`
* `flexberry-objectlistview`
=> Additional items into menu in each row

CHANGELOG.md, addon/controllers/detail-edit-form.js, addon/routes/edit-form.js
when performig transition to parent route after saving and changing deatil
model of 2nd level
=> Fix using of wrong model to get `id` param

CHANGELOG.md, addon/styles/components/flexberry-lookup.scss, app/templates/components/flexberry-lookup.hbs, app/templates/mobile/components/flexberry-lookup.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs
=> Fix mobile template of lexberry-lookup for adding loading

tests/dummy/app/controllers/components-examples/flexberry-file/settings-example.js
[TFS#120055](http://dis-tfs:8080/Common/CaseberrySupport/_workitems/edit/120055)
=> Fix `flexberry-file` example

CHANGELOG.md, app/templates/components/flexberry-simpleolv.hbs, tests/dummy/app/controllers/components-examples/flexberry-simpleolv/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-simpleolv/settings-example.hbs
[TFS#122289](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/122289)
=> Fix mobile `flexberry-simpleolv`

CHANGELOG.md, addon/components/flexberry-simpleolv.js, addon/mixins/olv-toolbar-controller.js, tests/dummy/app/controllers/components-examples/flexberry-simpleolv/settings-example.js
[TFS#122463](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/122463)
=> Fix for `flexberry-simpleolv`

tests/dummy/app/components/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-simpleolv/settings-example.js, tests/dummy/app/routes/components-examples/flexberry-simpleolv/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/settings-example.hbs, tests/dummy/app/templates/components-examples/flexberry-simpleolv/settings-example.hbs, tests/dummy/app/templates/components/settings-example.hbs
TFS #120343
PS in templates flexberry-simpleolv  modelProjection=modelProjection, if use computable property "projection" then example does not work.
=> fix settings-example olv

tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/hierarchy-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/hierarchy-example.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/hierarchy-example.hbs
=> Add example for hierarchy.

CHANGELOG.md, addon/mixins/flexberry-groupedit-route.js
when transitioning to detail edit form
=> Fix redundant saving of agregator

CHANGELOG.md, app/templates/i-i-s-caseberry-logging-objects-application-log-l.hbs, app/templates/new-platform-flexberry-services-lock-list.hbs, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/log-service-examples/clear-log-form.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/log-service-examples/clear-log-form.js, tests/dummy/app/templates/log-service-examples/clear-log-form.hbs, tests/dummy/config/environment.js
* Fix template for log and locks lists.
* Add form for batch log records delete (backend will now support new OData function for this).
* Add local development environment for config.
=> Fix log list recordsTotalCount parameter and much more

CHANGELOG.md, addon/components/flexberry-simpledatetime.js, app/templates/components/flexberry-simpledatetime.hbs, tests/dummy/app/controllers/components-examples/flexberry-simpledatetime/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-simpledatetime/settings-example.hbs
[TFS#126709](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/126709).
=> Fixes for `flexberry-simpledatetime`

CHANGELOG.md, app/templates/components/flexberry-menu.hbs
[TFS#126718](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/126718).
=> Fix `flexberry-menu` root items

tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js
=> Feature 125866 translate column names

tests/dummy/app/models/components-examples/flexberry-groupedit/shared/aggregator.js, tests/dummy/app/routes/components-examples/flexberry-groupedit/configurate-row-example.js
Fix test for Configurate row in fge.
=> Fix test for Configurate row in fge.

CHANGELOG.md, addon/components/flexberry-lookup.js, addon/controllers/lookup-dialog.js, addon/mixins/flexberry-lookup-controller.js, addon/mixins/flexberry-objectlistview-on-edit-form-controller.js, addon/mixins/sortable-controller.js, addon/mixins/sortable-route.js, addon/services/user-settings.js, addon/utils/deserialize-sorting-param.js, addon/utils/serialize-sorting-param.js, app/utils/deserialize-sorting-param.js, app/utils/serialize-sorting-param.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/default-ordering-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/models/ember-flexberry-dummy-suggestion.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-lookup/default-ordering-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/default-ordering-example.hbs, tests/unit/utils/deserialize-sorting-param-test.js, tests/unit/utils/serialize-sorting-param-test.js
Add ability to set default ordering for `flexberry-lookup` component
=> Add ability to set default ordering

CHANGELOG.md, addon/components/flexberry-objectlistview.js
=> Fixes for `flexberry-simpleolv` component

tests/unit/instance-initializers/moment-test.js
=> add test for instance-initializer moment

tests/unit/instance-initializers/i18n-test.js
=> add test for instance-initializer i18n

CHANGELOG.md, addon/components/flexberry-simpledatetime.js
Fix wrong timezone storing when using component to choose date without time
=> Fix wrong timezone storing

.gitignore, CHANGELOG.md, blueprints/flexberry-addon/AddonBlueprint.js, blueprints/flexberry-addon/AddonBlueprint.ts, blueprints/flexberry-edit-form/index.js, blueprints/flexberry-edit-form/index.ts, blueprints/flexberry-enum/index.js, blueprints/flexberry-enum/index.ts, blueprints/flexberry-group/index.js, blueprints/flexberry-group/index.ts, blueprints/flexberry-list-form/index.js, blueprints/flexberry-list-form/index.ts, blueprints/flexberry-model/index.js, blueprints/flexberry-model/index.ts, blueprints/flexberry-object/index.js, blueprints/flexberry-object/index.ts, blueprints/tsconfig.json
=> Add support reexport for addon

CHANGELOG.md, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts
=> Feature generation not stored attributes of models

CHANGELOG.md, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts, blueprints/flexberry-model/files/__root__/mixins/regenerated/serializers/__name__.js, blueprints/flexberry-serializer-init/files/__root__/serializers/__name__.js
=> Feature generation of serializers when inheriting models

CHANGELOG.md, blueprints/flexberry-core/index.js, blueprints/flexberry-core/index.ts, blueprints/typings/MetadataClasses.d.ts, vendor/flexberry/dummy-metadata/application/sitemap.json
=> Feature generation mobile templates

addon/styles/themes/blue-sky/collections/breadcrumb.overrides, addon/styles/themes/blue-sky/collections/form.overrides, addon/styles/themes/blue-sky/collections/menu.overrides, addon/styles/themes/blue-sky/collections/menu.variables, addon/styles/themes/blue-sky/collections/table.overrides, addon/styles/themes/blue-sky/elements/button.overrides, addon/styles/themes/blue-sky/elements/button.variables, addon/styles/themes/blue-sky/elements/icon.overrides, addon/styles/themes/blue-sky/elements/icon.variables, addon/styles/themes/blue-sky/elements/input.overrides, addon/styles/themes/blue-sky/elements/segment.overrides, addon/styles/themes/blue-sky/globals/site.overrides, addon/styles/themes/blue-sky/globals/site.variables, addon/styles/themes/blue-sky/modules/checkbox.overrides, addon/styles/themes/blue-sky/modules/checkbox.variables, addon/styles/themes/blue-sky/modules/dropdown.overrides, app/templates/components/flexberry-lookup.hbs, tests/dummy/app/styles/app.less, tests/dummy/app/templates/components-examples/flexberry-dropdown/items-example.hbs
Deleted unnecessary !important. 
Add color variables.
Deleted flexberry-gis styles.
=> Fix blue sky theme

CHANGELOG.md, blueprints/flexberry-core/index.js, blueprints/flexberry-core/index.ts, blueprints/flexberry-group/index.js, blueprints/flexberry-group/index.ts, blueprints/flexberry-model-init/files/__root__/models/__name__.js, blueprints/flexberry-model-init/index.js, blueprints/flexberry-model-init/index.ts, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts, blueprints/flexberry-serializer-init/files/__root__/serializers/__name__-offline.js, blueprints/flexberry-serializer-init/files/__root__/serializers/__name__.js, blueprints/flexberry-serializer-init/index.js, blueprints/flexberry-serializer-init/index.ts, blueprints/typings/MetadataClasses.d.ts
[#152451](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/152451)
=> Fix generation apps with external entities

CHANGELOG.md, addon/components/flexberry-simpleolv.js, addon/components/object-list-view.js, addon/mixins/flexberry-objectlistview-on-edit-form-controller.js, addon/mixins/limited-route.js
Added `like` condition for filters (for `string` type fields). It will be applied by default when condition is not set.
=> Feature 154688 filter by substring by default

blueprints/flexberry-edit-form/files/tests/dummy/app/templates/__name__.hbs, blueprints/flexberry-list-form/files/tests/dummy/app/templates/__name__.hbs
Forgot to update the generation templates for dummy app.
=> Fix flexberry-list-form and flexberry-edit-form blueprints

CHANGELOG.md, addon/routes/list-form.js
Fix reset of loading state on list forms when promise model was rejected
=> Fix reset of loading state on list forms

CHANGELOG.md, addon/components/flexberry-simpledatetime.js
Fix change related model value after clearing date when value was set programmatically in `flexberry-simpledatetime` component
=> Fix change related model value after clearing date

CHANGELOG.md, addon/helpers/get-with-dynamic-actions.js
=> Update dynamic-actions helper

.travis.yml, scripts/test-generator.sh, testem.js, testem.json, tests/acceptance/components/flexberry-objectlistview/folv-date-format-moment-test.js
Change PhantomJS to Headless Chrome
=> Fix test folv date format moment test

addon/components/flexberry-lookup.js, addon/locales/en/translations.js, addon/locales/ru/translations.js
Fix translate message for lookup
=> Fix translate message for lookup

addon/components/flexberry-lookup.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/autocomplete-order-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-lookup/autocomplete-order-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/autocomplete-order-example.hbs
Add OrderBy for Master in lookup and example
=> Add OrderBy for Master in lookup and example

CHANGELOG.md, addon/components/flexberry-objectlistview.js, addon/components/object-list-view-row.js, addon/locales/en/translations.js, addon/locales/ru/translations.js, addon/mixins/flexberry-objectlistview-hierarchical-controller.js, addon/styles/themes/blue-sky/elements/button.overrides, app/templates/components/flexberry-objectlistview.hbs, app/templates/components/object-list-view-row.hbs, app/templates/components/object-list-view.hbs, app/templates/components/olv-toolbar.hbs, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/hierarchy-example.hbs, tests/dummy/app/templates/components-examples/flexberry-objectlistview/settings-example.hbs
Add button collapse/expand mode all hierarchy in objectlistview
=> 157386 collapse expand objectlistview

CHANGELOG.md, addon/components/flexberry-objectlistview.js, addon/components/object-list-view-row.js, addon/mixins/flexberry-objectlistview-hierarchical-controller.js, addon/mixins/flexberry-objectlistview-hierarchical-route.js
=> Update load record for hierarchy

CHANGELOG.md, addon/styles/themes/blue-sky/globals/site.overrides, blueprints/flexberry-core/files/__root__/templates/mobile/application.hbs, tests/dummy/app/styles/app.less, tests/dummy/app/templates/mobile/application.hbs
=> Fix header height in `blue-sky` theme

CHANGELOG.md, addon/components/olv-toolbar.js, addon/mixins/limited-controller.js, app/templates/components/olv-toolbar.hbs, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/custom-filter.js, tests/dummy/app/controllers/components-examples/flexberry-simpleolv/custom-filter.js
Fix applying filtering by all fields by pressing `Enter` in IE for `flexberry-objectlistview` component
=> Fix applying filtering by all fields

app/templates/components/object-list-view-row.hbs
Issue:
http://techforum.ics.perm.ru/default.aspx?g=posts&t=2313#post11834
=> Fix hierarchy with nested nodes with checkboxes

.travis.yml, CHANGELOG.md, addon/components/flexberry-checkbox.js, app/templates/components/flexberry-checkbox.hbs, testem.js, testem.json
=> Checkbox fixes to support IE

addon/components/flexberry-lookup.js
155240: Limit the number of search elements requested in the auto-complete mode
=> Add top in bulder autocomplite

CHANGELOG.md, addon/components/flexberry-simpleolv.js
[TFS#159242](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/159242).
=> Set default user settings in `flexberry-simpleolv`

CHANGELOG.md, addon/components/object-list-view-row.js, app/templates/components/object-list-view-row.hbs, app/templates/components/object-list-view.hbs, app/templates/mobile/components/object-list-view-row.hbs
=> Fix hierarchy collapse and expand

tests/dummy/app/routes/components-examples/flexberry-objectlistview/hierarchy-example.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/on-edit-form.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/hierarchy-example.hbs
Fix wrong names of components in some pages of dummy application
=> Fix wrong names of components

app/templates/components/flexberry-simpleolv.hbs, app/templates/components/object-list-view.hbs
Hide select all buttons, when groupedit is readonly
=> Correct groupedit readonly at seelct all

CHANGELOG.md, addon/components/flexberry-groupedit.js, addon/components/groupedit-toolbar.js, addon/locales/en/translations.js, addon/locales/ru/translations.js, addon/mixins/lock-route.js, addon/routes/edit-form.js, addon/styles/themes/blue-sky/elements/button.overrides, app/templates/components/flexberry-groupedit.hbs, app/templates/components/groupedit-toolbar.hbs, tests/dummy/app/routes/ember-flexberry-dummy-suggestion-edit/new.js
=> Add column width saving for ge

CHANGELOG.md, addon/helpers/readonly-cell.js, app/templates/components/flexberry-simpleolv.hbs, app/templates/components/object-list-view-row.hbs
=> Fix work readonly in olv

CHANGELOG.md, addon/components/flexberry-simpleolv.js
=> Fix show default setting

CHANGELOG.md, addon/services/log.js, tests/unit/services/log-test.js
=> Add modulePrefix from environment in log

CHANGELOG.md, addon/components/flexberry-groupedit.js
=> Fix sort user setting in ge

CHANGELOG.md, addon/locales/en/translations.js, addon/locales/ru/translations.js, addon/routes/list-form.js
=> Correct error message

blueprints/flexberry-core/files/addon/locales/en/translations.js, blueprints/flexberry-core/files/addon/locales/ru/translations.js, blueprints/flexberry-core/index.js, blueprints/flexberry-core/index.ts
=> Fix generation translations

CHANGELOG.md, addon/components/flexberry-lookup.js, tests/dummy/app/routes/components-examples/flexberry-lookup/default-ordering-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/default-ordering-example.hbs
=> Fix lookup example

CHANGELOG.md, addon/components/flexberry-simpledatetime.js
for `flexberry-simpledatetime` component in IE.
=> Fix clear button in readonly mode

tests/acceptance/components/flexberry-dropdown/flexberry-dropdown-conditional-render-test.js, tests/acceptance/components/flexberry-dropdown/flexberry-dropdown-empty-value-test.js
Afther accept delete "Автоматизация теста проверка flexberry-dropdown: Пример условного рендеринга" and "Проверка flexberry-dropdown: dropdown с пустым значением"  test
=> Feature 162452 add dropdown tests

tests/acceptance/components/flexberry-groupedit/flexberry-groupedit configurate-row-test.js
Afther accept delete "Flexberry-groupedit: проверка configurate row (настройка строк)" test
=> Add  ge configurate row test

tests/acceptance/components/base-flexberry-lookup-test.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/limit-function-through-dynamic-properties-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/limit-function-through-dynamic-properties-example.hbs
Afther accept delete "Проверка flexberry-lookup: Функция ограничения через динамические свойства" test
=> Add flexberry lookup limit function through dynamic properties test

addon/routes/list-form.js, tests/acceptance/components/flexberry-objectlistview/folv-sorting-test.js, tests/acceptance/components/flexberry-objectlistview/folv-sorting-with-default-setting-test.js
=> Feature 162297 add check sorting with default setting test

tests/dummy/app/controllers/components-examples/flexberry-lookup/hierarchy-olv-in-lookup-example.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/hierarchy-example.js
Setting the default hierarchy for olv and lookup
=> Setting the default hierarchy for olv and lookup

addon/components/olv-toolbar.js, addon/mixins/limited-controller.js, addon/mixins/limited-route.js, addon/routes/list-form.js, addon/services/store.js, tests/acceptance/components/flexberry-objectlistview/folv-edit-button-in-row-test.js, tests/dummy/app/services/store.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/custom-filter.hbs
TFS #160200 
Merge this pullrequest after https://github.com/Flexberry/ember-flexberry-data/pull/111 and updating "ember-flexberry-data"
=> Feature 160200 delete all select record

addon/services/user-settings.js
=> Fix save user-settings

addon/components/colsconfig-dialog-content.js
TFS: [#164194](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/164194).
=> Show loader at apply user settings

CHANGELOG.md, addon/components/object-list-view-row.js, addon/components/olv-toolbar.js, tests/acceptance/edit-form-validation-test/validation-test.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/default-ordering-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/default-ordering-example.hbs
\+ Function in `buttonAction` for custom buttons in `flexberry-objectlistview` component.
=> Set default sorting for flexberry-lookup on test form

addon/mixins/flexberry-objectlistview-on-edit-form-controller.js
Fix example for olv on editform
=> Fix example for olv on editform

CHANGELOG.md, addon/components/colsconfig-dialog-content.js, addon/components/flexberry-objectlistview.js, addon/components/flexberry-simpleolv.js, addon/components/object-list-view.js, addon/components/olv-toolbar.js, addon/controllers/edit-form.js, addon/mixins/errorable-route.js, addon/mixins/flexberry-groupedit-route.js, addon/mixins/flexberry-objectlistview-on-edit-form-controller.js, addon/mixins/limited-controller.js, addon/routes/edit-form.js, addon/routes/list-form.js, addon/services/app-state.js, addon/services/objectlistview-events.js, app/services/app-state.js, app/templates/components/colsconfig-dialog-content.hbs, blueprints/flexberry-core/files/__root__/controllers/application.js, blueprints/flexberry-core/files/__root__/templates/application.hbs, blueprints/flexberry-core/files/__root__/templates/mobile/application.hbs, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/mobile/application.hbs, tests/unit/services/app-state-test.js
=> App sate service

CHANGELOG.md, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts, blueprints/flexberry-model/files/__root__/mixins/regenerated/models/__name__.js, blueprints/flexberry-model/index.js, blueprints/flexberry-model/index.ts
=> Generating valid default values for enumerations

CHANGELOG.md, addon/components/object-list-view.js, addon/mixins/flexberry-objectlistview-route.js, addon/routes/edit-form-new.js, addon/routes/edit-form.js
=> Update params fot opening editforms

CHANGELOG.md, addon/components/object-list-view.js
=> Fix error create new record in GE

CHANGELOG.md, addon/mixins/lock-route.js, yarn.lock
=> Fix lock route

CHANGELOG.md, addon/components/flexberry-file.js
=> fix file preview

CHANGELOG.md, addon/components/flexberry-objectlistview.js, addon/components/flexberry-simpleolv.js, app/templates/components/flexberry-simpleolv.hbs, app/templates/components/olv-toolbar.hbs, tests/acceptance/components/flexberry-objectlistview/folv-user-button-test.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/toolbar-custom-buttons-example.js, tests/dummy/app/controllers/components-examples/flexberry-simpleolv/toolbar-custom-buttons-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/toolbar-custom-buttons-example.hbs, tests/dummy/app/templates/components-examples/flexberry-simpleolv/toolbar-custom-buttons-example.hbs
=> Disabling custom buttons in list components

CHANGELOG.md, addon/mixins/flexberry-objectlistview-route.js, addon/mixins/lock-route.js, addon/routes/edit-form.js
=> fix return to perent route

CHANGELOG.md, addon/components/flexberry-lookup.js
=> Fixed semantic dropdown initialization for dropdown mode

CHANGELOG.md, addon/components/flexberry-lookup.js, addon/components/object-list-view-row.js, addon/locales/en/translations.js, addon/locales/ru/translations.js, addon/mixins/flexberry-lookup-controller.js, addon/styles/addon.less, addon/styles/themes/blue-sky/modules/modal.overrides, app/templates/components/flexberry-lookup.hbs, tests/dummy/app/controllers/ember-flexberry-dummy-suggestion-edit.js, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs
=> Add preview button in lookup

tests/dummy/app/models/ember-flexberry-dummy-comment-vote.js
=> Add validations in dummy model

.travis.yml, tests/dummy/config/environment.js
Use backend from docker to run tests in travis build.
=> Backend from docker in travis build

CHANGELOG.md, addon/mixins/dynamic-properties.js, tests/dummy/app/controllers/components-examples/flexberry-groupedit/ember-flexberry-dummy-suggestion-edit-groupedit-with-lookup-with-computed-atribute.js
=> Fix dynamic-properties mixin

CHANGELOG.md, addon/components/flexberry-lookup.js
=> Fix query creation in flexberry-lookup component

CHANGELOG.md, addon/components/flexberry-groupedit.js, addon/components/flexberry-objectlistview.js, addon/components/flexberry-simpleolv.js, app/templates/components/flexberry-groupedit.hbs, app/templates/components/flexberry-objectlistview.hbs, app/templates/components/flexberry-simpleolv.hbs, app/templates/components/object-list-view.hbs, app/templates/mobile/components/flexberry-objectlistview.hbs, app/templates/mobile/components/flexberry-simpleolv.hbs, tests/dummy/app/controllers/components-examples/flexberry-groupedit/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/settings-example.js, tests/dummy/app/controllers/components-examples/flexberry-simpleolv/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-groupedit/settings-example.hbs, tests/dummy/app/templates/components-examples/flexberry-objectlistview/settings-example.hbs, tests/dummy/app/templates/components-examples/flexberry-simpleolv/settings-example.hbs
=> Add flag to hide button

CHANGELOG.md, app/templates/components/object-list-view.hbs, tests/acceptance/components/flexberry-groupedit/flexberry-groupedit-check-all-at-page-test.js
=> Feature 773 ge select all button

CHANGELOG.md, addon/components/flexberry-simpleolv.js, addon/components/object-list-view.js, addon/mixins/olv-toolbar-controller.js, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts, tests/dummy/app/models/ember-flexberry-dummy-suggestion.js
=> Add index property generation for projection attributes

CHANGELOG.md, addon/components/flexberry-button.js, addon/mixins/dom-actions.js
=> Fix 777 flexberry button

CHANGELOG.md, addon/components/flexberry-lookup.js, tests/acceptance/components/flexberry-lookup/flexberry-lookup-autofill-by-limit-test.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-acceptance-tests/flexberry-lookup/settings-example-autofill-by-limit.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/autofill-by-limit-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-acceptance-tests/flexberry-lookup/settings-example-autofill-by-limit.js, tests/dummy/app/routes/components-examples/flexberry-lookup/autofill-by-limit-example.js, tests/dummy/app/templates/components-acceptance-tests/flexberry-lookup/settings-example-autofill-by-limit.hbs, tests/dummy/app/templates/components-examples/flexberry-lookup/autofill-by-limit-example.hbs
=> Feature 776 autofill by limit

CHANGELOG.md, addon/components/flexberry-groupedit.js, addon/components/groupedit-toolbar.js, addon/components/object-list-view.js, addon/services/objectlistview-events.js, addon/styles/themes/blue-sky/elements/button.overrides, app/templates/components/flexberry-groupedit.hbs, app/templates/components/groupedit-toolbar.hbs, app/templates/components/object-list-view.hbs, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts, blueprints/typings/MetadataClasses.d.ts, package-lock.json, package.json, tests/dummy/app/models/ember-flexberry-dummy-suggestion-file.js, tests/dummy/app/models/integration-examples/edit-form/readonly-mode/detail.js
=> Add logic for order property

CHANGELOG.md, blueprints/flexberry-model/ModelBlueprint.js, blueprints/flexberry-model/ModelBlueprint.ts
=> Fix index property generation for projection belongsTo attributes

CHANGELOG.md, addon/components/flexberry-file.js, addon/mixins/flexberry-file-controller.js, app/templates/flexberry-file-view-dialog.hbs, tests/dummy/app/controllers/components-examples/flexberry-file/flexberry-file-in-modal.js, tests/dummy/app/templates/components-examples/flexberry-file/flexberry-file-in-modal.hbs
=> add preview modal dialog options

CHANGELOG.md, addon/components/flexberry-lookup.js, app/templates/components/flexberry-lookup.hbs, tests/dummy/app/controllers/components-examples/flexberry-lookup/settings-example.js, tests/dummy/app/styles/app.less, tests/dummy/app/templates/components-examples/flexberry-lookup/settings-example.hbs
Add select first autocomplete result by enter click.
Add dropdown class to flexberry-lookup at drodpdown mode.
Resolve #798
=> Add select first autocomplete result by enter click

CHANGELOG.md, addon/components/flexberry-lookup.js, tests/dummy/app/controllers/components-examples/flexberry-groupedit/ember-flexberry-dummy-suggestion-edit-groupedit-with-lookup-with-computed-atribute.js
=> Add lookup limit at ge row

tests/dummy/app/templates/ember-flexberry-dummy-suggestion-edit.hbs, yarn.lock
Update ember-flexberry-data to ember-flexberry-data@2.1.0. Сhange date control for suggestion: add flexberry-simpledatetime/
=> Update ember-flexberry-data, change date suggestion

addon/components/flexberry-simpledatetime.js, addon/locales/en/translations.js, addon/locales/ru/translations.js, tests/integration/components/flexberry-simpledatetime-test.js
=> Add locale title to simpeldatetime month

tests/dummy/app/controllers/components-examples/flexberry-file/flexberry-file-in-modal.js, tests/dummy/app/templates/components-examples/flexberry-file/flexberry-file-in-modal.hbs
=> Feature 182475 remove ui modal from example

CHANGELOG.md, addon/mixins/reload-list-mixin.js
=> Fix hierarchy paging

CHANGELOG.md, app/templates/components/flexberry-lookup.hbs, tests/dummy/app/components/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/settings-example.hbs, tests/dummy/app/templates/components/settings-example.hbs
=> Fix lookup readonly mode

addon/mixins/olv-toolbar-controller.js
=> Fix list's column header caption

addon/components/object-list-view.js
=> Fix olv filter input cursor when fixedHeader is true

CHANGELOG.md, addon/components/object-list-view.js, addon/components/olv-toolbar.js, app/templates/components/object-list-view.hbs
=> Fix filters applying by `Enter` click

CHANGELOG.md, addon/services/offline-globals.js, app/services/offline-globals.js, package.json, tests/dummy/app/services/offline-globals.js
=> Add offline globals

blueprints/flexberry-core-offline/index.js
=> Add method create offline schema

CHANGELOG.md, app/templates/mobile/components/flexberry-objectlistview.hbs, app/templates/mobile/components/object-list-view-row.hbs, app/templates/mobile/components/object-list-view.hbs
=> Feature 879 add paging hierarchy at mobile

CHANGELOG.md, addon/components/flexberry-text-cell.js, addon/components/object-list-view-cell.js, addon/utils/cut-string-by-length.js, app/components/flexberry-text-cell.js, app/templates/components/flexberry-text-cell.hbs, app/templates/components/object-list-view-cell.hbs, app/utils/cut-string-by-length.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-objectlistview/limited-text-size-example.js, tests/dummy/app/controllers/components-examples/flexberry-text-cell/settings-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-objectlistview/limited-text-size-example.js, tests/dummy/app/routes/components-examples/flexberry-text-cell/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-objectlistview/limited-text-size-example.hbs, tests/dummy/app/templates/components-examples/flexberry-text-cell/settings-example.hbs, tests/dummy/app/templates/components/settings-example.hbs, tests/unit/utils/cut-string-by-length-test.js
=> Add flexberry-text-cell component

addon/components/flexberry-simpledatetime.js, addon/locales/en/translations.js, addon/locales/ru/translations.js, addon/styles/themes/blue-sky/collections/form.overrides
=> Feature 895 correct simpledatetime placeholder

addon/components/colsconfig-dialog-content.js
=> Fix 892 user settings

addon/components/colsconfig-dialog-content.js, app/templates/components/colsconfig-dialog-content.hbs
=> Fix colsconfig-dialog-content.js

tests/dummy/app/templates/ember-flexberry-dummy-multi-list-user-edit.hbs
=> Fix edit form from multi-list open.

addon/components/flexberry-simpledatetime.js, app/templates/components/flexberry-simpledatetime.hbs
New button for opening flatpickr, can still be opened by clicking on input
=> flexberry-simpledatetime open flatpickr button

addon/styles/themes/blue-sky/collections/menu.overrides, addon/styles/themes/blue-sky/modules/dropdown.overrides
=> fix: olv toolbar menu and pagination ie bug

addon/components/flexberry-simpleolv.js
=> fix: Fix simpleolv fixed header bug from Android & IOS

CHANGELOG.md, addon/mixins/flexberry-lookup-compatible-component.js, addon/styles/themes/blue-sky/elements/button.overrides, app/templates/mobile/components/flexberry-lookup.hbs, tests/dummy/app/controllers/components-examples/flexberry-lookup/settings-example.js, tests/dummy/app/controllers/ember-flexberry-dummy-suggestion-edit.js, tests/dummy/app/templates/components-examples/flexberry-lookup/settings-example.hbs
=> Add mobile lookup show

addon/components/flexberry-lookup.js
=> Issues 940 fix points at lookup autokomplete

addon/mixins/errorable-route.js
Resolve #946 Добавлен вызов super
=> Добавление вызова super в errorable-route в resetController

CHANGELOG.md, addon/components/flexberry-groupedit.js, app/templates/components/flexberry-groupedit.hbs, tests/dummy/app/controllers/components-examples/flexberry-groupedit/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-groupedit/settings-example.hbs
=> Groupedit header fix

CHANGELOG.md, addon/components/flexberry-lookup.js, tests/dummy/app/controllers/components-examples/flexberry-lookup/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-lookup/settings-example.hbs
=> Add pagination for autocomplete in flexberrry-lookup component

CHANGELOG.md, addon/routes/list-form.js, blueprints/flexberry-list-form/files/app/templates/__name__.hbs
=> Add modelName in list-form controller

CHANGELOG.md, addon/components/flexberry-lookup.js
=> Fix 983 lookup loader circle

CHANGELOG.md, addon/components/flexberry-lookup.js, addon/mixins/flexberry-lookup-controller.js, app/templates/lookup-dialog.hbs
=> Add modal dialog settings for flexberry-lookup component

CHANGELOG.md, addon/components/object-list-view.js
=> Fix applaying invalid user settings in object-list-view component

CHANGELOG.md, addon/components/flexberry-objectlistview.js, addon/components/olv-toolbar.js, app/templates/components/flexberry-objectlistview.hbs, app/templates/lookup-dialog-content.hbs
One of the cases of issue #958.
=> Fix component name passed to modal window in some cases

addon/components/flexberry-lookup.js, app/templates/components/flexberry-lookup.hbs
=> Затирание текста при focusOut лукапа в автокомплите

addon/components/flexberry-file.js, tests/dummy/app/controllers/components-examples/flexberry-file/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-file/settings-example.hbs
Fix Flexberry/ember-flexberry#751
=> Issue 751. Flexberry-file works with base64

blueprints/ember-flexberry/index.js, blueprints/flexberry-edit-form/index.js, blueprints/flexberry-edit-form/index.ts, blueprints/flexberry-edit-form/snippets/flexberry-checkbox.hbs, blueprints/flexberry-edit-form/snippets/flexberry-dropdown.hbs, blueprints/flexberry-edit-form/snippets/flexberry-field.hbs, blueprints/flexberry-edit-form/snippets/flexberry-file.hbs, blueprints/flexberry-edit-form/snippets/flexberry-groupedit.hbs, blueprints/flexberry-edit-form/snippets/flexberry-lookup.hbs, blueprints/flexberry-edit-form/snippets/flexberry-simpledatetime.hbs, blueprints/flexberry-edit-form/snippets/flexberry-textbox.hbs
=> Генерация ember-test-selectors

addon/components/flexberry-dropdown.js, addon/styles/addon.less, addon/styles/themes/blue-sky/modules/sidebar.overrides
=> Дропдаун правильно открывается в контексте window

tests/dummy/app/templates/modal/ember-flexberry-support-modal.hbs
Стили для формы обратной связи были вынесены в тему.
=> Стили для формы обратной связи

tests/dummy/app/templates/login.hbs
=> Login form

addon/components/flexberry-validationmessage.js, theme.config
Styles: https://github.com/Flexberry/ember-flexberry-themes/pull/75
#1090
=> Fix validation styles

app/templates/components/flexberry-objectlistview.hbs
Styles: https://github.com/Flexberry/ember-flexberry-themes/pull/76
=> Fix search page button styles

blueprints/flexberry-edit-form/index.js, blueprints/flexberry-edit-form/index.ts
Исправление некорректной генерации data-test-selectors на шаблоне формы редактирования
=> Фикс генерации названий у data-test-selectors

package.json, tests/acceptance/components/readonly-test/edit-form-readonly-test.js, tests/dummy/app/templates/components-acceptance-tests/edit-form-readonly.hbs, yarn.lock
=> Change readonly test to ember-test-selectors usage

blueprints/flexberry-core/files/theme.config, theme.config
Added uimessage component, sorted Controls block
=> Added uimessage component

app/templates/mobile/components/colsconfig-dialog-content.hbs, tests/dummy/app/templates/mobile/application.hbs
Styles: https://github.com/Flexberry/ember-flexberry-themes/pull/87
=> Fix user icon image and remove ui-dropdown

addon/components/flexberry-groupedit.js
=> searchForContentChange default value change

addon/components/flexberry-menu.js, addon/components/mobile/object-list-view.js, app/templates/mobile/components/flexberry-objectlistview.hbs, app/templates/mobile/components/object-list-view.hbs
=> Fix row selection menu in mobile flexberry-objectlistview

addon-test-support/check-delete-record-from-olv.js, addon-test-support/index.js, tests/.jshintrc, tests/acceptance/components/flexberry-objectlistview/folv-delete-record-from-olv-test.js, tests/dummy/app/templates/components-acceptance-tests/flexberry-objectlistview/folv-paging.hbs
=> Add test helper for check delete from olv

addon-test-support/index.js, addon-test-support/open-editform.js, tests/.jshintrc, tests/acceptance/components/flexberry-objectlistview/folv-goto-editform-test.js
=> test-helper-for-open-editform

addon-test-support/check-delete-record-from-e-form.js, addon-test-support/index.js, addon-test-support/utils/create-recort-for-test.js, tests/.jshintrc, tests/acceptance/components/flexberry-objectlistview/folv-delete-record-from-e-form-test.js, tests/dummy/app/templates/components-acceptance-tests/flexberry-objectlistview/folv-paging.hbs
=> Add delete from E form test helper

addon-test-support/check-close-edit-form.js, addon-test-support/index.js, tests/.jshintrc, tests/acceptance/components/flexberry-objectlistview/folv-close-from-edit-form-test.js, tests/dummy/app/templates/components-acceptance-tests/flexberry-objectlistview/folv-paging.hbs
=> Add close e form test helper

addon-test-support/check-lookup-dialogs.js, addon-test-support/index.js, app/templates/components/flexberry-lookup.hbs, app/templates/lookup-dialog-content.hbs, app/templates/lookup-dialog.hbs
=> Add lookup dialog test helper

addon/locales/en/translations.js, addon/locales/ru/translations.js, app/templates/i-i-s-caseberry-logging-objects-application-log-l/loading.hbs, blueprints/flexberry-core/files/__root__/templates/loading.hbs, blueprints/flexberry-core/files/tests/dummy/app/templates/loading.hbs, blueprints/flexberry-list-form/files/app/templates/__name__/loading.hbs, blueprints/flexberry-list-form/files/tests/dummy/app/templates/__name__/loading.hbs, tests/dummy/app/templates/components-examples/flexberry-objectlistview/edit-form-with-detail-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-application-user-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-comment-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-localization-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-multi-user-suggestion-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-file-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-list/loading.hbs, tests/dummy/app/templates/ember-flexberry-dummy-suggestion-type-list/loading.hbs
=> Translate loading text

addon/components/flexberry-lookup.js, addon/controllers/lookup-dialog.js, addon/mixins/flexberry-lookup-controller.js, addon/services/lookup-events.js, tests/unit/controllers/lookup-dialog-test.js
=> Add updateLookupAction when selecting new value from lookup modal

addon/components/flexberry-toggler.js, addon/styles/themes/blue-sky/modules/accordion.overrides, addon/styles/themes/blue-sky/modules/accordion.variables, addon/styles/themes/default/modules/accordion.variables, tests/dummy/app/controllers/components-examples/flexberry-toggler/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-toggler/settings-example.hbs, tests/integration/components/flexberry-toggler-test.js
Also added tests for relevant properties
=> Added hasShadow and hasBorder properties for flexberry-toggler

addon/mixins/edit-form-controller-operations-indication.js, package.json
Now notifications will appear after first Save-button click.
=> Fixed edit-from's save notifications.

addon/controllers/edit-form.js
=> Add validation to edit-form controller.

.github/workflows/node.js.yml
За основу взят Travis https://github.com/Flexberry/ember-flexberry/blob/develop/.travis.yml
Оставшиеся проблемы с генерацией документации:
- непонятно как обрабатывать ситуацию  $TRAVIS_PULL_REQUEST != "false"  - неизвестно содержимое переменной $GITHUB_EVENT_NAME при pull/...
- https://github.com/kafnevod/ember-flexberry/runs/1490617255?check_suite_focus=true
При выполнении скрипта 
bash scripts/deploy-to-gh-pages.sh 
ошибок не наблюдается, но код завершения 128!
=> Добавление GitHub Action

CHANGELOG.md, addon/services/device.js, tests/unit/services/device-test.js
=> fix device

CHANGELOG.md, addon/routes/edit-form-new.js, tests/unit/routes/edit-form-new-test.js
=> Fix return promise from model in new route

addon/components/flexberry-sitemap.js, app/templates/components/flexberry-sitemap.hbs, blueprints/flexberry-core/files/__root__/controllers/index.js, blueprints/flexberry-core/files/__root__/templates/application.hbs, blueprints/flexberry-core/files/__root__/templates/index.hbs, blueprints/flexberry-core/index.js, blueprints/flexberry-list-form/files/app/templates/__name__.hbs
Close #1264,
Styles: https://github.com/Flexberry/ember-flexberry-themes/pull/99
=> Fix blueprints and sitemap component

tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js
Fixed and supplemented localization for English.
=> Fix translations sitemap
